name: imdb_sql
description: IMDB Sample DB
publish_to: 'none'
version: 0.0.1+1-pre

environment:
  sdk: ^2.12.0

dependencies:
  moor: ^4.3.0
  path: ^1.8.0
  args: ^2.1.0
  multiline: ^3.0.0

dev_dependencies:
  moor_generator: ^4.3.0
  build_runner: ^2.0.3
